name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign user
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X POST -d '{"assignees": ["github-actions[bot]"]}' 
          https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/assignees
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Install Dependencies
        run: npm install
      - name: Build and Deploy
        run: |
          npm install -g angular-cli-ghpages@1.0.5
          ng build --prod --base-href "https://LordPrinz.github.io/angularQuiz/"
          npx angular-cli-ghpages --dir=dist/projekt --no-silent
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
